FROM centos:7.9.2009 as build

WORKDIR /tmp
RUN curl -o rust.sh https://sh.rustup.rs -sSf \
 && chmod a+x rust.sh \
 && ./rust.sh -y -q --profile minimal \
 && rm rust.sh

RUN ln -s /root/.cargo/bin/* /usr/local/bin

RUN yum groupinstall -y "Development Tools"

WORKDIR /opt/app/src
COPY . .

RUN cargo build --release

FROM centos:7.9.2009

COPY --from=build /opt/app/src/target/release/chipper /usr/local/bin

ENTRYPOINT ["chipper"]
